GET http://localhost:5079/games

###
GET http://localhost:5079/games/1

###
POST http://localhost:5079/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genre": "Kids and Family",
    "price": 19.99,
    "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5079/games/1
Content-Type: application/json

{
    "name": "GTA 4",
    "genre": "Action",
    "price": 25.5,
    "releaseDate": "2013-07-15"
}

###
DELETE http://localhost:5079/games/1